### PR TITLE
Bump version to 3.5.1

### PR DESCRIPTION
**Pull request by Anthchirp**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
re SPDX warning: project doesn't have a proper license file. Only mentions "Public Domain" in its setup.py.

Couldn't find a relevant source repository either, so didn't notify authors.

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Please consider adding yourself as a maintainer here.

**Review by smithsp — APPROVED** [review]

**Comment by smithsp** [comment]
@Anthchirp Thanks for the PR.  Feel free to add yourself as a maintainer in a new PR.  I just thought I would merge this one while it was passing and I was here.

**Comment by Anthchirp** [comment]
done in #4 🙂

**Pull request merged**
